from lark import Transformer

class LarkTransformer(Transformer):
    """
    Create a transformer that takes in the parse tree generated by the parser and that returns a string
    with letters A-Z, numbers 0-9, and spaces which is the translation of the Morse code (based on the international standard).
    The translation table is below:
    A: .-
    B: -...
    C: -.-.
    D: -..
    E: .
    F: ..-.
    G: --.
    H: ....
    I: ..
    J: .---
    K: -.-
    L: .-..
    M: --
    N: -.
    O: ---
    P: .--.
    Q: --.-
    R: .-.
    S: ...
    T: -
    U: ..-
    V: ...-
    W: .--
    X: -..-
    Y: -.--
    Z: --..
    0: -----
    1: .----
    2: ..---
    3: ...--
    4: ....-
    5: .....
    6: -....
    7: --...
    8: ---..
    9: ----.
    """